language: java
jdk: openjdk7
install:
  - scripts/install-chrome.sh
  - scripts/install-appengine.sh
script:
  - cd $TRAVIS_BUILD_DIR/extension && npm test
  - cd $TRAVIS_BUILD_DIR/galactichorse/src/main/webapp && npm test
notifications:
  email: false
