language: java
jdk: openjdk7
notifications:
  email: false
before_install:
  - openssl aes-256-cbc -K $encrypted_fa93c5106312_key -iv $encrypted_fa93c5106312_iv -in galactic-horse-a4beb2236124.json.enc -out galactic-horse-a4beb2236124.json -d
install:
- scripts/install-chrome.sh
- scripts/install-appengine.sh
script:
- cd $TRAVIS_BUILD_DIR/extension && npm test
- cd $TRAVIS_BUILD_DIR/galactichorse/src/main/webapp && npm test
before_deploy:
- cd $TRAVIS_BUILD
- mv galactichorse/* ./
- rm -rf extension scripts galactichorse
deploy:
  provider: gae
  keyfile: galactic-horse-a4beb2236124.json
  skip_cleanup: true
  default: true
  project: galactic-horse
